### ISSUE TITLE
Poller - Writeup query

### ISSUE THREAD

**Issue by itsdivyanshjain** [c0g4ih4l4n/ctf-writeups#1]
How did you deserialize the django cookie using the secret token.

I have already tried:
```
from django.core import signing
from django.contrib.sessions.serializers import PickleSerializer 
SECRET_KEY = 'django-insecure-fnxu@v&(wqd%77m6p#k_s2+n5na-bqe!m)^zu)9typ#0c&8o6!'

print(signing.loads(cookie,key=SECRET_KEY, salt='django.contrib.sessions.backends.signed_cookies', serializer=PickleSerializer ))
```

but not working for me.

**Comment by c0g4ih4l4n** [comment]
The error would help for me.
Or you can try this. 
```python
import os
import subprocess
import pickle
from django.core import signing
from django.contrib.sessions.serializers import PickleSerializer

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")

s = '.eJxNjEEKwjAQRXXhUgRPoZvQpE3S7MS9ZyiTycRWpYW2WQoeIMt4Dq9oRYX-5XuP_1g9X4vv7mkX1xWEsa7CQH3VuBSXeYrbGbOAV2onsXcXaM8dw64d-8ayT8J-dmCnztHt-G83s4MahjrFg_WgeU5KeAA0oIUtfSmzAp3RmeKoFRjKfCmE9IZwktzmyEESL5RUmAJ7AxE7P6U:1nkgm5:WgzAWxxDDs29vtImFiH-jDffvCVvigsvYH-Kju_MIWg'

print (signing.loads(
    s,
    serializer=PickleSerializer,
    # This doesn't handle non-default expiry dates, see #19201
    salt='django.contrib.sessions.backends.signed_cookies',
))
```
And settings.py:
```python
SECRET_KEY=77m6p#v&(wk_s2+n5na-bqe!m)^zu)9typ#0c&@qd%8o6!
```

**Comment by itsdivyanshjain** [comment]
error is bad signature `django.core.signing.BadSignature`.

I think main reason is improper secret_token. I have used `SECRET_KEY = 'django-insecure-fnxu@v&(wqd%77m6p#k_s2+n5na-bqe!m)^zu)9typ#0c&8o6!'` as per this commit(https://github.com/congon4tor/poller/commit/ec8ac4687787cbb4418e0064154a018438d72e89) but you have mentioned different token which is `SECRET_KEY=77m6p#v&(wk_s2+n5na-bqe!m)^zu)9typ#0c&@qd%8o6!`. 

P.S: This error happens only when i tried to deserialize the production cookie, when I try to run it  locally i am able to deserialize it.

**Comment by itsdivyanshjain** [comment]
I have tried using your secret_token on production server of challenge and it does work. Can you tag the link of the commit here, where this secret_token is mentioned.

**Comment by itsdivyanshjain** [comment]
I got it. So, the secret I'm using is rabbit hole. And there is another secret_token which is inside .env file which is the real one.
